Added new image statistics plugin
Summary:
removed commented code

Removed Variance (can be computed from Standard deviation)

Added statistics dataNode

const correctness

Added module skeleton for custom HistogramWidget

Removed unused function

Used itk macros

Resolved T24201 Extracted StatisticsContainer class

Cleanup

Merge branch 'T24201-extractStatisticsContainer' into T24182-newImageStatisticsPlugin

Implemented public API and slots

Added SelectionComboBoxes for image and mask

Merge remote-tracking branch 'origin/T24204-QMitkHistogramVisualizationWidget' into T24182-newImageStatisticsPlugin

# Conflicts:
#	Plugins/org.mitk.gui.qt.measurementtoolbox/src/internal/QmitkImageStatisticsReloadedViewControls.ui

Removed unused Stack Widget

Changes according to styleguide

Changed the name of the ui file

Resolved T24203 Added QmitkImageStatisticsWidget

Merge branch 'T24204-QMitkHistogramVisualizationWidget' into T24182-newImageStatisticsPlugin

Implemented basic QmitkIntensityProfileVisualizationWidget

Updated both modules' layout to automatically resize

Resolved T24200 Implemented QmitkImageStatisticsTableModel

Added model in QmitkImageStatisticsWidget

Improved const correctness

Implemented first working plugin version (shows statistics)

Merge branch 'T24200-QmitkStatistics' into T24203-QmitkImageStatisticsWidget

Added DataNodes to TableModel instead of names

Added clear function

Adaptions to UI

Merge branch 'T24200-QmitkStatistics' into T24203-QmitkImageStatisticsWidget

Merge branch 'T24203-QmitkImageStatisticsWidget' into T24182-newImageStatisticsPlugin

Merge branch 'T24182-newImageStatisticsPlugin' of https://phabricator.mitk.org/source/mitk into T24182-newImageStatisticsPlugin

# Conflicts:
#	Modules/ImageStatisticsUI/files.cmake
#	Plugins/org.mitk.gui.qt.measurementtoolbox/src/internal/QmitkImageStatisticsReloadedViewControls.ui

Renamed functions for better consistency between QmitkImageStatisticsWidget and QmitkImageStatisticsWidget

Added functionality to display histogram

Fixed warning about layout reassignment

Set sizeHint for ChartWidget to stop it from growing to large vertically

Removed the outer groupBox

Resolved T24227 it's possible now to clear the mask.

Merge branch 'T24227-clearImageAndMask' into T24182-newImageStatisticsPlugin

Resolved T24280 added disconnect to selectors

Merge branch 'T24280-pluginCrashesWithMask' into T24182-newImageStatisticsPlugin

Resolved T24281

Merge branch 'T24281-resetHistogram' into T24182-newImageStatisticsPlugin

Don't display histogram visualization (ChartWidget) if Qt <5.10 is used

Removed unused label

removed duplicated groupbox string

Added size to C3js chart to initially adapt the size

removed unnecessary includes

adapted header size of statisticsView

Moved functions

Added function to disable all GUI elements

deactivated CopyToClipboard button as function is not yet implemented

Set 4D checkbox invisible as function is not yet implemented

Adapted background of QmitkChartWidget to active color theme

Merge branch 'T24282-cleanupUI' into T24182-newImageStatisticsPlugin

Reset the statistics widget before filling

Added volume to statisticsContainer and calculator

Removed unimplemented/unnecessary function definitions

Resolved T24254: statistics are now ordered like they were in the old plugin. QSortProxyModel not yet used, preparation for T24256

Display mask name in statisticsModel

Removed unneeded class

Moved QmitkImageStatisticsCalculationThread from Plugin to Module ImageStatisticsUI and renamed it to QmitkImageStatisticsCalculationJob.

Merge branch 'T24254-customOrderStatistics' into T24182-newImageStatisticsPlugin

Added default, min + max value for nBins (constrained in ImageStatisticsCalculator)

Resolved T24257: if nBins is changed, histogram is computed for desired bins.

Merge branch 'T24257-computeHistogramWithCustomBins' into T24182-newImageStatisticsPlugin

fixed T24326 image statistics are now also computed if plugin is visible

Merge branch 'T24326-imageStatisticsNotComputed' into T24182-newImageStatisticsPlugin

fixed T24334

Merge branch 'T24334-imageStatisticsNotUpdated' into T24182-newImageStatisticsPlugin

Fixed T24336

Merge branch 'T24336-resetGUIifReloaded' into T24182-newImageStatisticsPlugin

implemented QmitkTableModelToStringConverter (input: tablemodel, output: string)

resolved T24325: clipboard functionality implemented

Merge branch 'T24325-imageStatisticsClipboardFunctionality' into T24182-newImageStatisticsPlugin

Resolved T24246 statistics are computed inside planar figures

Merge branch 'T24246-closedPlanarFigure' into T24182-newImageStatisticsPlugin

Corrected include

Added version check for Qt 5.10 required for MitkChart

Added theme

Added intensity profile widget to UI

Resolved T24245 Intensity profile now shown

Merge branch 'T24245-intensityProfile' into T24182-newImageStatisticsPlugin

The image statistics can deal with images with multiple time steps now

Signed-off-by: Andre Klein <andre.klein@dkfz-heidelberg.de>

Merge remote-tracking branch 'origin/T24247-ImageStatisticsMultipleTimeSteps' into T24182-newImageStatisticsPlugin

# Conflicts:
#	Plugins/org.mitk.gui.qt.measurementtoolbox/src/internal/QmitkImageStatisticsReloadedView.cpp

Fixed some warning for gcc

Signed-off-by: Andre Klein <andre.klein@dkfz-heidelberg.de>

Merge branch 'T24639-linux-build-errors' into T24182-newImageStatisticsPlugin

# Conflicts:
#	Modules/ImageStatisticsUI/Qmitk/QmitkImageStatisticsTableModel.cpp

removed unncecessary function

resolved T24652 added min/max indices to statistics table

improved documentation

Merge branch 'T24652-addMaximumPosition' into T24182-newImageStatisticsPlugin

resolved T24645 displayed label "Calculating statistics..." when computing

Merge branch 'T24645-AddCalculateStatisticsWhenComputing' into T24182-newImageStatisticsPlugin

Merge branch 'T24182-newImageStatisticsPlugin' of https://phabricator.mitk.org/source/mitk into T24182-newImageStatisticsPlugin

# Conflicts:
#	Modules/ImageStatisticsUI/Qmitk/QmitkImageStatisticsTableModel.cpp

Merge branch 'T24182-newImageStatisticsPlugin' of ssh://phabricator.mitk.org:2222/source/mitk into T24182-newImageStatisticsPlugin

Some refactoring for a consistent format

Changed .js-file to initially resize the window on chart creation

Merge branch 'T24412-Maximize-histogram-initially' into T24182-newImageStatisticsPlugin

Resolved T24648: segmentations are now recognized in mask data storage combo box. Helper Nodes are not displayed anymore.

Merge branch 'T24648-segmentationsNotRecognized' into T24182-newImageStatisticsPlugin

workaround for T24729

Improved const correctness

Added statistics container as data node

resolved T24202: statistics container connected to image + mask

code improvement

removed unnecessary clone

Merge branch 'T24202-connectImageStatisticsContainerToImageAndMask' into T24182-newImageStatisticsPlugin

added rule for each input type

Added ImageStatisticsContainerManager and Test

For handling requests if imageStatistics of an image (+mask) is already computed

make variables const in CalculationJob

As Clone() of an object alters the UID

Caching of statistic objects in plugin

Statistic is only computed if not already in DataStorage

Encapsulation of GetStatisticsContainer and GetStatisticsValue

hotfix before T24729 is done

removed planarFigure from ImageStatisticsContainerManager

as it can be interpreted as mask

added documentation

simplifications

recompute statistics if input objects have changed

Added classes defining statistics relation

Comparison of Data instead of DataNode

MTime is compared if more than  2 nodes are found

Removed functions from helper class

Added test for returning only newest node

if multiple nodes are valid due to relation definition

Simplified CalculateStatistics function

Merge branch 'T24253-QmitkStatisticsContainerManagerNew' into T24182-newImageStatisticsPlugin

Revert "Encapsulation of GetStatisticsContainer and GetStatisticsValue"

This reverts commit 8ebdb8673fbcf4c12a4c19124d3c3541f664b378.

implemented ignore zero-valued method to statistics plugin.

Merge branch 'T24646-implementIgnoreZeroValuedVoxel' into T24182-newImageStatisticsPlugin

Added new basic Widget OmitkSliderSpinboxWidget, that combines a QSlider and a QSpinbox.

Signed-off-by: Clemens Hentschke <c.hentschke@dkfz-heidelberg.de>

Added QmitkSliderSpinboxWidget to QmitkImageStatisticsReloadedView. No Functionality yet, just a nice widget.

Signed-off-by: Clemens Hentschke <c.hentschke@dkfz-heidelberg.de>

Removed SliderSpinbox widget (same as ctkSliderWidget)

Added observer for image navigator time step change event Fix T24653

Corrected check for nullptr Fixes T25036

Added statistics reloaded plugin as stub

removed commented code

Removed Variance (can be computed from Standard deviation)

Added statistics dataNode

const correctness

Added module skeleton for custom HistogramWidget

Removed unused function

Used itk macros

Resolved T24201 Extracted StatisticsContainer class

Cleanup

Implemented public API and slots

Added ctkSliderWidget for timestep in histogram

Added SelectionComboBoxes for image and mask

Removed unused Stack Widget

Changes according to styleguide

Changed the name of the ui file

Resolved T24203 Added QmitkImageStatisticsWidget

Implemented basic QmitkIntensityProfileVisualizationWidget

Updated both modules' layout to automatically resize

Resolved T24200 Implemented QmitkImageStatisticsTableModel

Added model in QmitkImageStatisticsWidget

Improved const correctness

Implemented first working plugin version (shows statistics)

Added DataNodes to TableModel instead of names

Added clear function

Adaptions to UI

Renamed functions for better consistency between QmitkImageStatisticsWidget and QmitkImageStatisticsWidget

Added functionality to display histogram

Fixed warning about layout reassignment

Set sizeHint for ChartWidget to stop it from growing to large vertically

Removed the outer groupBox

Resolved T24227 it's possible now to clear the mask.

Resolved T24280 added disconnect to selectors

Resolved T24281

Don't display histogram visualization (ChartWidget) if Qt <5.10 is used

Removed unused label

removed duplicated groupbox string

Added size to C3js chart to initially adapt the size

removed unnecessary includes

adapted header size of statisticsView

Moved functions

Added function to disable all GUI elements

deactivated CopyToClipboard button as function is not yet implemented

Set 4D checkbox invisible as function is not yet implemented

Adapted background of QmitkChartWidget to active color theme

Reset the statistics widget before filling

Added volume to statisticsContainer and calculator

Removed unimplemented/unnecessary function definitions

Resolved T24254: statistics are now ordered like they were in the old plugin. QSortProxyModel not yet used, preparation for T24256

Display mask name in statisticsModel

Removed unneeded class

Moved QmitkImageStatisticsCalculationThread from Plugin to Module ImageStatisticsUI and renamed it to QmitkImageStatisticsCalculationJob.

Added default, min + max value for nBins (constrained in ImageStatisticsCalculator)

Resolved T24257: if nBins is changed, histogram is computed for desired bins.

fixed T24326 image statistics are now also computed if plugin is visible

fixed T24334

Fixed T24336

implemented QmitkTableModelToStringConverter (input: tablemodel, output: string)

resolved T24325: clipboard functionality implemented

Resolved T24246 statistics are computed inside planar figures

Corrected include

Added version check for Qt 5.10 required for MitkChart

Added theme

Added intensity profile widget to UI

Resolved T24245 Intensity profile now shown

The image statistics can deal with images with multiple time steps now

Signed-off-by: Andre Klein <andre.klein@dkfz-heidelberg.de>

Fixed some warning for gcc

Signed-off-by: Andre Klein <andre.klein@dkfz-heidelberg.de>

removed unncecessary function

resolved T24652 added min/max indices to statistics table

improved documentation

resolved T24645 displayed label "Calculating statistics..." when computing

Some refactoring for a consistent format

Changed .js-file to initially resize the window on chart creation

Resolved T24648: segmentations are now recognized in mask data storage combo box. Helper Nodes are not displayed anymore.

workaround for T24729

Improved const correctness

Added statistics container as data node

resolved T24202: statistics container connected to image + mask

code improvement

removed unnecessary clone

added rule for each input type

Added ImageStatisticsContainerManager and Test

For handling requests if imageStatistics of an image (+mask) is already computed

make variables const in CalculationJob

As Clone() of an object alters the UID

Caching of statistic objects in plugin

Statistic is only computed if not already in DataStorage

Encapsulation of GetStatisticsContainer and GetStatisticsValue

hotfix before T24729 is done

removed planarFigure from ImageStatisticsContainerManager

as it can be interpreted as mask

added documentation

simplifications

recompute statistics if input objects have changed

Added classes defining statistics relation

Comparison of Data instead of DataNode

MTime is compared if more than  2 nodes are found

Removed functions from helper class

Added test for returning only newest node

if multiple nodes are valid due to relation definition

Simplified CalculateStatistics function

Revert "Encapsulation of GetStatisticsContainer and GetStatisticsValue"

This reverts commit 8ebdb8673fbcf4c12a4c19124d3c3541f664b378.

implemented ignore zero-valued method to statistics plugin.

Added observer for image navigator time step change event Fix T24653

Corrected check for nullptr Fixes T25036

Merge branch 'T24650-computeHistogramCurrentTimestep' into T24182-newImageStatisticsPlugin

Connected the ctkSliderWidget to the histogram functionality for 4D images

Revert "Corrected check for nullptr Fixes T25036"

This reverts commit 801e1c0230e7295516577db68035860985aa6861.

Revert "Added observer for image navigator time step change event"

This reverts commit 8b12ef1f519f96b7d02b95bc4d0b2e1dcde280e7.

Merge branch 'T24650-computeHistogramIntegration' into T24182-newImageStatisticsPlugin

Fix some rebase errors. Rebased master T24783

Merge branch 'T24182-newImageStatisticsPlugin' of ssh://phabricator.mitk.org:2222/source/mitk into T24182-newImageStatisticsPlugin

ImageStatisticsUI: great again

Added timeSteps to StatisticContainer

Adjusted tests to account for timeSteps in StatisticContainers

Fixed compilation errors

Added TimeGeometry to clone function

Removed unnecessary dataChange()

Merge branch 'T25031-timesteps-container-improvement' into T24182-newImageStatisticsPlugin

fixed #timesteps to display

Merge branch 'T25439-sliderTimestepsHistogramIncorrect' into T24182-newImageStatisticsPlugin

Resolved T25448 by filtering the mask combobox by geometry of the image

Merge branch 'T25448-resetMaskOnImageChange' into T24182-newImageStatisticsPlugin

Using the member variable for the row count instead of a temporary

Merge branch T25447-adaptRowCountOfImageStatisticsTableModel

resolved T25474 fixed issues for gcc compiler

Merge branch 'T25474-gccCompileIssues' into T24182-newImageStatisticsPlugin

added new icon for the new image statistics plugin

Merge branch 'T25481-newIcon' into T24182-newImageStatisticsPlugin

Merge branch 'T24182-newImageStatisticsPlugin'

# Conflicts:
#	Modules/Chart/src/QmitkChartWidget.cpp
#	Plugins/org.mitk.gui.qt.measurementtoolbox/src/internal/QmitkImageStatisticsView.cpp

Test Plan: image statistics checklists are ok

Reviewers: O1 MITK Core, floca

Reviewed By: O1 MITK Core, floca

Subscribers: floca

Maniphest Tasks: T25474, T25448, T25036, T24653, T24652, T24648, T24645, T24336, T24334, T24326, T24325, T24281, T24280, T24257, T24254, T24246, T24245, T24227, T24203, T24202, T24201, T24200

Differential Revision: https://phabricator.mitk.org/D170