Fixes Builderror under Linux
Had to replace  mitk::Matrix< mitk::Point3D, 9, 10 >  in  mitkHummelProtocolEvaluation
with std::array<std::array<mitk::Point3D, 10> ,9> because
the mitk::Matrix-solution would not compile on Linux. It always gave an error message:
vnl_c_vector.h:42:49: error: invalid use of incomplete type ‘class vnl_numeric_traits<itk::Point<double, 3u> >’